<?php
/**
 * GeoReady — pure builders for the AI discovery artifacts.
 *
 * No WordPress calls live here: this class turns plain data (site name,
 * description, URL, a list of pages) into the text of llms.txt, ai.txt, and
 * ai/summary.json. Keeping it WP-free makes it unit-testable with plain PHP
 * and mirrors the astro-geoready integration's separation of concerns.
 *
 * @package GeoReady
 */

if ( ! defined( 'ABSPATH' ) && ! defined( 'GEOREADY_TEST' ) ) {
	exit; // No direct access (allowed only under the test harness).
}

/**
 * Stateless builders for llms.txt, ai.txt, and ai/summary.json.
 */
class GeoReady_Builder {

	/**
	 * Title-case a slug segment: "getting-started" -> "Getting Started".
	 *
	 * @param string $value Raw slug or title.
	 * @return string
	 */
	public static function humanize( $value ) {
		$value = trim( (string) $value );
		if ( '' === $value ) {
			return '';
		}
		$parts = preg_split( '/[-_\s]+/', $value );
		$parts = array_filter( $parts, 'strlen' );
		$parts = array_map(
			static function ( $word ) {
				return ucfirst( strtolower( $word ) );
			},
			$parts
		);
		return implode( ' ', $parts );
	}

	/**
	 * Build llms.txt from a list of pages grouped by section.
	 *
	 * @param array  $args  { site_name, description, site_url }.
	 * @param array  $pages List of [ 'title' => string, 'url' => string, 'section' => string ].
	 * @param int    $max_per_section Max links per section.
	 * @return string
	 */
	public static function build_llms_txt( array $args, array $pages, $max_per_section = 50 ) {
		$site_name   = isset( $args['site_name'] ) ? $args['site_name'] : '';
		$description = isset( $args['description'] ) ? $args['description'] : '';
		$site_url    = isset( $args['site_url'] ) ? rtrim( (string) $args['site_url'], '/' ) : '';

		$sections = array();
		foreach ( $pages as $page ) {
			$section = isset( $page['section'] ) && '' !== $page['section'] ? $page['section'] : 'Pages';
			if ( ! isset( $sections[ $section ] ) ) {
				$sections[ $section ] = array();
			}
			if ( count( $sections[ $section ] ) < $max_per_section ) {
				$sections[ $section ][] = $page;
			}
		}

		// "Pages" first, then alphabetical.
		uksort(
			$sections,
			static function ( $a, $b ) {
				if ( 'Pages' === $a ) {
					return -1;
				}
				if ( 'Pages' === $b ) {
					return 1;
				}
				return strcasecmp( $a, $b );
			}
		);

		$lines = array( '# ' . $site_name, '' );
		if ( '' !== $description ) {
			$lines[] = '> ' . $description;
			$lines[] = '';
		}
		foreach ( $sections as $section => $items ) {
			$lines[] = '## ' . $section;
			$lines[] = '';
			foreach ( $items as $item ) {
				$lines[] = '- [' . $item['title'] . '](' . $item['url'] . ')';
			}
			$lines[] = '';
		}
		$lines[] = 'Generated by the GeoReady plugin. Audit this site: https://geoready.dev';
		return implode( "\n", $lines ) . "\n";
	}

	/**
	 * Build /.well-known/ai.txt.
	 *
	 * @param array $args { site_name, site_url }.
	 * @return string
	 */
	public static function build_ai_txt( array $args ) {
		$site_name = isset( $args['site_name'] ) ? $args['site_name'] : '';
		$site_url  = isset( $args['site_url'] ) ? rtrim( (string) $args['site_url'], '/' ) : '';
		$lines     = array(
			'# ai.txt — AI crawler guidance for ' . $site_name,
			'',
			'User-Agent: *',
			'Allow: /',
			'',
			'Sitemap: ' . $site_url . '/sitemap.xml',
			'LLMs: ' . $site_url . '/llms.txt',
			'',
		);
		return implode( "\n", $lines );
	}

	/**
	 * Build /ai/summary.json.
	 *
	 * @param array $args  { site_name, description, site_url }.
	 * @param int   $count Number of indexed pages.
	 * @return string Pretty-printed JSON.
	 */
	public static function build_summary_json( array $args, $count ) {
		$data = array(
			'name'         => isset( $args['site_name'] ) ? $args['site_name'] : '',
			'description'  => isset( $args['description'] ) ? $args['description'] : '',
			'url'          => isset( $args['site_url'] ) ? rtrim( (string) $args['site_url'], '/' ) : '',
			'pages_count'  => (int) $count,
			'llms_txt'     => ( isset( $args['site_url'] ) ? rtrim( (string) $args['site_url'], '/' ) : '' ) . '/llms.txt',
			'generated_by' => 'wordpress-geoready',
		);
		if ( '' === $data['description'] ) {
			unset( $data['description'] );
		}
		return wp_json_encode_compat( $data ) . "\n";
	}
}

/**
 * JSON encode with pretty print, falling back gracefully outside WordPress
 * (the test harness has no wp_json_encode).
 *
 * @param mixed $data Data to encode.
 * @return string
 */
function wp_json_encode_compat( $data ) {
	return json_encode( $data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
}
